name: backend-ci
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false
      - name: Install dependencies
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: run
